/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import proyecto.LineasFactura;


/**
 *
 * @author AlumMati
 */
public class Facturas extends javax.swing.JFrame {
    static public ResultSet r2;
    static public ResultSet r3;
static public Connection connection;
  
    public Facturas() throws SQLException {
        initComponents();        
/*         aceptarbutton.setVisible(false);
        aceptarbutton.setVisible(false);
        cancelbutton.setEnabled(false);
        cancelbutton.setVisible(false);*/
         String url ="jdbc:mysql://localhost:3306/tiendaanimales";
        String user="root";
        String contra="";
        connection = DriverManager.getConnection(url,user,contra);        
        regenerardatos();
     
       
    }
     public void regenerardatos() throws SQLException{
        Statement s = (Statement) connection.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
        String query="SELECT * FROM FACTURAS";
        r3=s.executeQuery(query);
        r3.first();
        Identificador.setText(r3.getString("IdFactura"));
        PrecioTotal.setText(r3.getString("Precio"));
        Fechancala.setText(r3.getString("Fecha"));
        }
     public String giveme(){
         String codigo=Identificador.getText();
         return codigo;
     }
       public int nuevafactura() throws SQLException{
            Statement s = (Statement) connection.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
            String numfactquery= "SELECT MAX(IdFactura)+1 as uno,CURDATE() as fecha FROM FACTURAS";
            r2=s.executeQuery(numfactquery);
            int a=0;
            String fecha="";
            if(r2.next()){
                a=r2.getInt("uno");
                fecha=r2.getString("fecha");
            }
            String inser="INSERT INTO facturas(IdFactura,Fecha) SELECT MAX(IdFactura)+1,CURDATE() FROM FACTURAS";
            int b=s.executeUpdate(inser);  
            
            
            regenerardatos();
            return a;
       }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        PrecioTotal = new javax.swing.JTextField();
        Fechancala = new javax.swing.JTextField();
        anteriorbutton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        siguientebutton = new javax.swing.JButton();
        Identificador = new javax.swing.JTextField();
        primerobutton = new javax.swing.JButton();
        modificar = new javax.swing.JButton();
        ultimobutton = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        nuevobutton1 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(590, 300));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Identificador");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, -1, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Precio total");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Fecha");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        PrecioTotal.setEditable(false);
        PrecioTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrecioTotalActionPerformed(evt);
            }
        });
        PrecioTotal.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                PrecioTotalKeyTyped(evt);
            }
        });
        getContentPane().add(PrecioTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 255, -1));

        Fechancala.setEditable(false);
        Fechancala.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FechancalaActionPerformed(evt);
            }
        });
        getContentPane().add(Fechancala, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, 255, -1));

        anteriorbutton.setText("Anterior");
        anteriorbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anteriorbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(anteriorbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 90, 87, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Facturas");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        siguientebutton.setText("Siguiente");
        siguientebutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                siguientebuttonActionPerformed(evt);
            }
        });
        getContentPane().add(siguientebutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 90, 91, -1));

        Identificador.setEditable(false);
        Identificador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IdentificadorActionPerformed(evt);
            }
        });
        Identificador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                IdentificadorKeyTyped(evt);
            }
        });
        getContentPane().add(Identificador, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, 255, -1));

        primerobutton.setText("Primero");
        primerobutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                primerobuttonActionPerformed(evt);
            }
        });
        getContentPane().add(primerobutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 140, 91, -1));

        modificar.setText("Modificar");
        modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarActionPerformed(evt);
            }
        });
        getContentPane().add(modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 190, 87, -1));

        ultimobutton.setText("Ultimo");
        ultimobutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ultimobuttonActionPerformed(evt);
            }
        });
        getContentPane().add(ultimobutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 140, 87, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/foto2.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 10, 62, 51));

        nuevobutton1.setText("Nuevo");
        nuevobutton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nuevobutton1ActionPerformed(evt);
            }
        });
        getContentPane().add(nuevobutton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 190, 87, -1));

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 240, 91, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/bosque.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 580, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IdentificadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IdentificadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IdentificadorActionPerformed

    private void PrecioTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrecioTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PrecioTotalActionPerformed

    private void FechancalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FechancalaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FechancalaActionPerformed

    private void anteriorbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anteriorbuttonActionPerformed
        try {
            if(r3.previous()){
                 Identificador.setText(r3.getString("IdFactura"));
                 PrecioTotal.setText(r3.getString("Precio"));
                 Fechancala.setText(r3.getString("Fecha"));
            }} catch (SQLException ex) {
            Logger.getLogger(Facturas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_anteriorbuttonActionPerformed

    private void siguientebuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_siguientebuttonActionPerformed
        try {
            if(r3.next()){
                 Identificador.setText(r3.getString("IdFactura"));
                 PrecioTotal.setText(r3.getString("Precio"));
                 Fechancala.setText(r3.getString("Fecha"));
            }} catch (SQLException ex) {
            Logger.getLogger(Facturas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_siguientebuttonActionPerformed

    private void primerobuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_primerobuttonActionPerformed
        try {
            r3.first();
              Identificador.setText(r3.getString("IdFactura"));
                 PrecioTotal.setText(r3.getString("Precio"));
                 Fechancala.setText(r3.getString("Fecha"));
        } catch (SQLException ex) {
            Logger.getLogger(Facturas.class.getName()).log(Level.SEVERE, null, ex);
        }
      
    }//GEN-LAST:event_primerobuttonActionPerformed

    private void ultimobuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ultimobuttonActionPerformed
             try {
            r3.last();
              Identificador.setText(r3.getString("IdFactura"));
                 PrecioTotal.setText(r3.getString("Precio"));
                 Fechancala.setText(r3.getString("Fecha"));
        } catch (SQLException ex) {
            Logger.getLogger(Facturas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ultimobuttonActionPerformed

    private void modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarActionPerformed
        int este=Integer.parseInt(Identificador.getText());
        
        try {
            LineasFactura far = new LineasFactura();
            far.setVisible(true);
            this.setVisible(false);
            far.setFactura(este);
            far.setLocationRelativeTo(null);
        } catch (SQLException ex) {
            Logger.getLogger(Facturas.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        
    }//GEN-LAST:event_modificarActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Login log = new Login();
        this.setVisible(false);
        log.setVisible(true);
       log.setLocationRelativeTo(null);
                
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Menu menyo=new Menu();
        this.setVisible(false);
        menyo.setVisible(true);
        menyo.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void nuevobutton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nuevobutton1ActionPerformed
        try {                
            int nuevo;
            nuevo = nuevafactura();
        if(r3.last()){
            Identificador.setText(r3.getString("IdFactura"));
                 PrecioTotal.setText(r3.getString("Precio"));
                 Fechancala.setText(r3.getString("Fecha"));
        }
         
           LineasFactura far = new LineasFactura();
            far.setVisible(true);
            far.setFactura(nuevo);
            this.setVisible(false);
            far.setLocationRelativeTo(null);
        } catch (SQLException ex) {
            Logger.getLogger(Facturas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_nuevobutton1ActionPerformed

    private void IdentificadorKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_IdentificadorKeyTyped
  char a = evt.getKeyChar();
        if (!Character.isDigit(a)) {
            evt.consume();
        }    }//GEN-LAST:event_IdentificadorKeyTyped

    private void PrecioTotalKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_PrecioTotalKeyTyped
  char a = evt.getKeyChar();
        if (!Character.isDigit(a)) {
            evt.consume();
        }    }//GEN-LAST:event_PrecioTotalKeyTyped

    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Fechancala;
    private javax.swing.JTextField Identificador;
    private javax.swing.JTextField PrecioTotal;
    private javax.swing.JButton anteriorbutton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton modificar;
    private javax.swing.JButton nuevobutton1;
    private javax.swing.JButton primerobutton;
    private javax.swing.JButton siguientebutton;
    private javax.swing.JButton ultimobutton;
    // End of variables declaration//GEN-END:variables

}
