/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author AlumMati
 */
public class ProductosVisualiza extends javax.swing.JFrame {

    static public ResultSet r;
    static public ResultSet r2a;
    static public ResultSet r3;
    static public Connection connection;

    /**
     * Creates new form ProductosVisualiza
     */
    public ProductosVisualiza() throws SQLException {
        initComponents();
        Connection con = null;
         String url ="jdbc:mysql://localhost:3306/tiendaanimales";
        String user="root";
        String contra="";
        connection = DriverManager.getConnection(url, user, contra);

        Statement s = (Statement) connection.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
        regenerardatos();
    }

    public String metodoquery() throws SQLException {
        String cat = (String) combo2.getSelectedItem();
        String query;

        if (cat == "cuidados") {
            query = "select * from cuidados";
        } else if (cat == "complementos") {
            query = "select * from complementos";
        } else {
            query = "select * from objetos";
        }
        return query;
    }

    public void regenerardatos() throws SQLException {        
        String query = metodoquery();
        Statement s2 = connection.createStatement();
        r = s2.executeQuery(query);
        if (combo2.getSelectedItem()!="objetos") {
        String tipo = null;
        if (r.next()) {
            ident1.setText(r.getString("identificador"));
            tipo = r.getString("Tipo");
            namae.setText(r.getString("Nombre"));
            desc.setText(r.getString("Descripcion"));
        }
        recuperartipo(tipo);
        }else{
            if (r.next()) {
            ident1.setText(r.getString("identificador"));
            namae.setText(r.getString("Nombre"));
            desc.setText(r.getString("Descripcion"));
        }
        }
    }
    

    public void recuperartipo(String tipo) throws SQLException {
        DefaultComboBoxModel value1 = new DefaultComboBoxModel();
        String dameanimal = "SELECT * FROM animales WHERE IdAnimal=" + tipo;
        Statement s2 = connection.createStatement();
        r3 = s2.executeQuery(dameanimal);

        if (r3.next()) {
            value1.addElement(r3.getString("Animal"));
        }
        combotipo.setModel(value1);    }
    
  

    public String dameidanimal() throws SQLException {
        String Animal1 = (String) combotipo.getSelectedItem();
        String id1 = "";
        String busquedaid = "SELECT * FROM animales WHERE Animal='" + Animal1 + "'";
        Statement s2 = connection.createStatement();
        r3 = s2.executeQuery(busquedaid);
        if (r3.next()) {
            id1 = r3.getString("IdAnimal");
        }
        return id1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ident1 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        combotipo = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        namae = new javax.swing.JTextField();
        desc = new javax.swing.JTextField();
        combo2 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        tipoh = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ident1.setEditable(false);
        ident1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ident1ActionPerformed(evt);
            }
        });
        getContentPane().add(ident1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 269, -1));

        jButton6.setText("Salir");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 360, 81, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Identificador");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, -1, -1));

        combotipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        combotipo.setEnabled(false);
        combotipo.setFocusable(false);
        getContentPane().add(combotipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 269, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Descripción");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nombre");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, -1, -1));

        namae.setEditable(false);
        getContentPane().add(namae, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, 269, -1));

        desc.setEditable(false);
        getContentPane().add(desc, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 269, -1));

        combo2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "cuidados", "complementos", "objetos" }));
        combo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo2ActionPerformed(evt);
            }
        });
        getContentPane().add(combo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 269, -1));

        jButton1.setText("Siguiente");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 130, 100, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Categoría");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, -1, -1));

        jButton3.setText("Anterior");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, 90, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/foto2.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 40, 62, 51));

        jButton4.setText("Primero");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 200, 90, -1));

        tipoh.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        tipoh.setForeground(new java.awt.Color(255, 255, 255));
        tipoh.setText("Tipo");
        getContentPane().add(tipoh, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        jButton5.setText("Ultimo");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 200, 100, -1));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/bosque.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void combo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo2ActionPerformed

        try {
            if (combo2.getSelectedItem() == "objetos") {
                combotipo.setVisible(false);               
                tipoh.setVisible(false);
                regenerardatos();
            } else {
                combotipo.setVisible(true);                
                tipoh.setVisible(true);
                regenerardatos();
            }
        } catch (SQLException ex) {
            Logger.getLogger(ProductosVisualiza.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_combo2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Login log = new Login();
        log.setVisible(true);
        log.setLocationRelativeTo(null);
        this.setVisible(false);
        log.setLocationRelativeTo(null);

    }//GEN-LAST:event_jButton2ActionPerformed

    private void ident1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ident1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ident1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            if (combo2.getSelectedItem() != "objetos") {
            String tipo = "";
            if (r.next()) {
                ident1.setText(r.getString("identificador"));
                tipo = r.getString("Tipo");
                namae.setText(r.getString("Nombre"));
                desc.setText(r.getString("Descripcion"));
                recuperartipo(tipo);
            }            
            }else{
                if (r.next()) {
                ident1.setText(r.getString("identificador"));
                namae.setText(r.getString("Nombre"));
                desc.setText(r.getString("Descripcion"));
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(ProductosVisualiza.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
           try {
            if (combo2.getSelectedItem() != "objetos") {
            String tipo = "";
            if (r.previous()) {
                ident1.setText(r.getString("identificador"));
                tipo = r.getString("Tipo");
                namae.setText(r.getString("Nombre"));
                desc.setText(r.getString("Descripcion"));
                recuperartipo(tipo);
            }            
            }else{
                if (r.previous()) {
                ident1.setText(r.getString("identificador"));
                namae.setText(r.getString("Nombre"));
                desc.setText(r.getString("Descripcion"));
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(ProductosVisualiza.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            if (combo2.getSelectedItem() != "objetos") {
            String tipo = "";
            if (r.first()) {
                ident1.setText(r.getString("identificador"));
                tipo = r.getString("Tipo");
                namae.setText(r.getString("Nombre"));
                desc.setText(r.getString("Descripcion"));
                recuperartipo(tipo);
            }            
            }else{
                if (r.first()) {
                ident1.setText(r.getString("identificador"));
                namae.setText(r.getString("Nombre"));
                desc.setText(r.getString("Descripcion"));
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(ProductosVisualiza.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
         try {
            if (combo2.getSelectedItem() != "objetos") {
            String tipo = "";
            if (r.last()) {
                ident1.setText(r.getString("identificador"));
                tipo = r.getString("Tipo");
                namae.setText(r.getString("Nombre"));
                desc.setText(r.getString("Descripcion"));
                recuperartipo(tipo);
            }            
            }else{
                if (r.last()) {
                ident1.setText(r.getString("identificador"));
                namae.setText(r.getString("Nombre"));
                desc.setText(r.getString("Descripcion"));
                }
            }
        } catch (SQLException ex) {
            Logger.getLogger(ProductosVisualiza.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        Menu menyo=new Menu();
        this.setVisible(false);
        menyo.setVisible(true);
        menyo.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> combo2;
    private javax.swing.JComboBox<String> combotipo;
    private javax.swing.JTextField desc;
    private javax.swing.JTextField ident1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField namae;
    private javax.swing.JLabel tipoh;
    // End of variables declaration//GEN-END:variables
}
