/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.event.ListDataListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author AlumMati
 */
public class ProductosFactura extends javax.swing.JFrame {
static public ResultSet r;
static public ResultSet r2a;
static public ResultSet r3;
static public Connection connection;

    /**
     * Creates new form ProductosFactura
     */
    public ProductosFactura() throws SQLException {      
        initComponents();        
        idobjet.setVisible(false);       
          Connection con = null;
        Login log = new Login();
        String url ="jdbc:mysql://localhost:3306/tiendaanimales";
        String user="Dependiente";
        String contra="roto2";
        connection = DriverManager.getConnection(url,user,contra);
        
        Statement s = (Statement) connection.createStatement(ResultSet.TYPE_SCROLL_SENSITIVE, ResultSet.CONCUR_UPDATABLE);
        metodoquery();
        
    }
    public void metodoquery() throws SQLException{      
         String cat=(String)combo1.getSelectedItem();
        String query;
      
          if(cat=="cuidados"){
         query="select * from cuidados";
         }
        else if(cat=="complementos"){
         query="select * from complementos";  
        }
        else{
         query="select * from objetos";
        }
        Statement s2 = connection.createStatement();
        r = s2.executeQuery(query);
        
        DefaultComboBoxModel value1 = new DefaultComboBoxModel();
        
        while(r.next()){
            value1.addElement(r.getString("Nombre"));
        }
        combo2.setModel(value1); 
        String cosa = (String) combo2.getSelectedItem();
        String query2="SELECT * FROM "+cat+" WHERE Nombre='"+cosa+"'";
         Statement s3 = connection.createStatement();
        r2a = s3.executeQuery(query2);
        r2a.next();
        idobjet.setText(r2a.getString("Articulo"));
    }
   
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jFrame2 = new javax.swing.JFrame();
        botonagregar = new javax.swing.JButton();
        idobjet = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        Punidad = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Ptotal = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        exist = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        txtcant = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        combo1 = new javax.swing.JComboBox<>();
        combo2 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonagregar.setText("Calcular");
        botonagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonagregarActionPerformed(evt);
            }
        });
        getContentPane().add(botonagregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 250, 97, -1));

        idobjet.setText("Identificador");
        idobjet.setEnabled(false);
        idobjet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idobjetActionPerformed(evt);
            }
        });
        getContentPane().add(idobjet, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, -1, -1));

        jButton1.setText("Salir");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 380, 81, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Precio por unidad");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));

        Punidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PunidadActionPerformed(evt);
            }
        });
        getContentPane().add(Punidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 107, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Precio total");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, -1, -1));

        Ptotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PtotalActionPerformed(evt);
            }
        });
        getContentPane().add(Ptotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 155, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Existencias");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 210, -1, -1));

        exist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                existActionPerformed(evt);
            }
        });
        getContentPane().add(exist, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 250, 100, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Consultar precio Productos");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Producto");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, -1, -1));

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/foto2.png"))); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 310, 62, 51));

        txtcant.setText("1");
        txtcant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcantActionPerformed(evt);
            }
        });
        getContentPane().add(txtcant, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 140, 69, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Cantidad");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 90, -1, -1));

        combo1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "cuidados", "complementos", "objetos" }));
        combo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo1ActionPerformed(evt);
            }
        });
        getContentPane().add(combo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));

        combo2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        combo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combo2ActionPerformed(evt);
            }
        });
        getContentPane().add(combo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 394, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Categoría");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, -1, -1));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/bosque.jpg"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 700, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idobjetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idobjetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idobjetActionPerformed

    private void botonagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonagregarActionPerformed
        try {
          
            String idobjetoo=idobjet.getText();
            String consulta = "Select LOL.Precio,LOL.Existencias,SUM(LOL.Precio*"+txtcant.getText()+")AS lol FROM articulos LOL WHERE LOL.Articulo="+idobjetoo;
            Statement s4 = connection.createStatement();            
            r3 = s4.executeQuery(consulta);
            r3.next();        
            Punidad.setText(r3.getString("LOL.Precio"));
            Ptotal.setText(r3.getString("lol"));
            exist.setText(r3.getString("LOL.Existencias"));
            /*
            if(preciototal.getText().equalsIgnoreCase("0")){
                String colocar=r3.getString("lol");
            }
            float colocar=Float.parseFloat(preciototal.getText())+Float.parseFloat(r3.getString("lol"));
            String coloco=Float.toString(colocar);
            preciototal.setText(coloco);*/
        } catch (SQLException ex) {
            Logger.getLogger(ProductosFactura.class.getName()).log(Level.SEVERE, null, ex);
        }catch(Exception E){
            System.out.println("Excepcion " +E.getMessage());
        }
    }//GEN-LAST:event_botonagregarActionPerformed

    private void combo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combo2ActionPerformed

    private void combo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combo1ActionPerformed
        try {
            metodoquery();
        } catch (SQLException ex) {
            Logger.getLogger(ProductosFactura.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_combo1ActionPerformed

    private void txtcantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtcantActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Menu menyo=new Menu();
        this.setVisible(false);
        menyo.setVisible(true);
        menyo.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void PunidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PunidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PunidadActionPerformed

    private void PtotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PtotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PtotalActionPerformed

    private void existActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_existActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_existActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
           Login log = new Login();
        log.setVisible(true);
        log.setLocationRelativeTo(null);
        this.setVisible(false);
        try {
            log.desconectar();
        } catch (SQLException ex) {
            Logger.getLogger(Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Ptotal;
    private javax.swing.JTextField Punidad;
    private javax.swing.JButton botonagregar;
    private javax.swing.JComboBox<String> combo1;
    private javax.swing.JComboBox<String> combo2;
    private javax.swing.JTextField exist;
    private javax.swing.JTextField idobjet;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txtcant;
    // End of variables declaration//GEN-END:variables
}
